name: build-docker-image

on:
  pull_request:
   
  push:    
    branches:
      - pipeline-test
#      - releases/*

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and test
      run: |
        npm install
        npm run build 

  build_docker_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build . --file Dockerfile --tag neuralegion/brokencrystals
      - name: Login into Docker
        run: docker login --username=anatol1988 --password=${{ secrets.DOCKER_TOKEN }}
      - name: Push Docker image
        run: docker push neuralegion/brokencrystals
